
apiVersion: v1
kind: Secret
metadata:
  labels: 
    app.kubernetes.io/instance: test-chatbot-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-chatbot-1 
  name: model-endpoint-secret
type: Opaque
data:
  MODEL_ENDPOINT_SECRET: {{ .Values.modelEndpointSecret | b64enc | quote }}